### ISSUE TITLE
brew install tccli failed

### ISSUE THREAD

**Issue by syslxg** [TencentCloud/homebrew-tccli#4]
$ brew install tccli
==> Downloading https://formulae.brew.sh/api/formula.jws.json
####################################################################################################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
####################################################################################################################################################### 100.0%
==> Fetching tencentcloud/tccli/tccli
==> Downloading https://github.com/TencentCloud/tencentcloud-cli/archive/3.0.953.1.tar.gz
==> Downloading from https://codeload.github.com/TencentCloud/tencentcloud-cli/tar.gz/refs/tags/3.0.953.1
               -=O=-                  #          #          #            #
==> Installing tccli from tencentcloud/tccli
==> python3 -m venv --system-site-packages --without-pip /opt/homebrew/Cellar/tccli/3.0.953.1/libexec
==> /opt/homebrew/Cellar/tccli/3.0.953.1/libexec/bin/pip install -v /private/tmp/tccli-20230907-5685-19d0iga/tencentcloud-cli-3.0.953.1
Last 15 lines from /Users/garyliu/Library/Logs/Homebrew/tccli/02.pip:
2023-09-08 03:58:50 +0000

/opt/homebrew/Cellar/tccli/3.0.953.1/libexec/bin/pip
install
-v
--ignore-installed
/private/tmp/tccli-20230907-5685-19d0iga/tencentcloud-cli-3.0.953.1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/tencentcloud/homebrew-tccli/issues

**Comment by rustin-huang** [comment]
Same problem.
Machine: M2 Pro

**Comment by scoooooott** [comment]
Same. Chip: M1 Pro

**Comment by im23cn** [comment]
Same. Chip: M1 Pro

**Comment by syslxg** [comment]
I worked around this problem by `pip3 install tccli`

**Comment by alanhe421** [comment]
![image](https://github.com/user-attachments/assets/cb4dc4f1-b204-40b6-ae60-71136a0ae7aa)
